FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 5000
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /Wishgranter
COPY ["WishGranter.csproj", "."]
COPY ["/ratstash_jsons/", "/app/ratstash_jsons/"]
RUN dotnet restore "./WishGranter.csproj"
COPY . .
WORKDIR "/Wishgranter/." 
RUN dotnet build "WishGranter.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WishGranter.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WishGranter.dll"]