name: BE-pipeline-dev
on:
  push:
    branches:
      - dev-*
      - feat-*
      - fix-*
    paths:
      - BackEnd/**
  pull_request:
    branches:
      - main

## Remember:
# ${{ env.WISHGRANTER_API_URL }}     // for env
# ${{ secrets.AWS_ACCESS_KEY_ID }}   // for secrets
# ${{ vars.EB_REGION }}              // for repo vars

## If you need to find something
# - name: Display structure of files 
#   run: ls -R

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-BE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Create nuget.config
        run: |
          echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>" > nuget.config
          echo "<configuration>" >> nuget.config
          echo "  <packageSources>" >> nuget.config
          echo "    <add key=\"GitHub\" value=\"https://nuget.pkg.github.com/Xerxes-17/index.json\" />" >> nuget.config
          echo "  </packageSources>" >> nuget.config
          echo "  <packageSourceCredentials>" >> nuget.config
          echo "    <GitHub>" >> nuget.config
          echo "      <add key=\"Username\" value=\"${{ github.actor }}\" />" >> nuget.config
          echo "      <add key=\"ClearTextPassword\" value=\"${{ secrets.GH_PACKAGES_TOKEN }}\" />" >> nuget.config
          echo "    </GitHub>" >> nuget.config
          echo "  </packageSourceCredentials>" >> nuget.config
          echo "</configuration>" >> nuget.config

      - name: Restore dependencies
        run: dotnet restore ./WishGranter.sln
        working-directory: ./BackEnd/WishGranter

      - name: Publish
        run: dotnet publish ./WishGranter.sln -r linux-x64 -c Release --self-contained true -o ./publish
        working-directory: ./BackEnd/WishGranter
